import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-black text-white">
      <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
        <Link
          href="/"
          className="mb-8 inline-flex items-center gap-2 text-sm text-white/40 transition-colors hover:text-white/70"
        >
          <span>←</span>
          <span>Back to Home</span>
        </Link>

        <div className="ios-glass rounded-3xl p-8 sm:p-10 space-y-8">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tight bg-gradient-to-r from-white via-slate-200 to-slate-400 bg-clip-text text-transparent">
              Terms of Service
            </h1>
            <p className="text-xs text-white/25">Effective Date: June 15, 2026</p>
          </div>

          <p className="text-sm leading-relaxed text-white/50">
            By accessing and using Digital Daily (&quot;the Platform&quot;), you
            agree to follow and be bound by the following Terms of Service. If you
            do not agree to these terms, please discontinue use of the platform.
          </p>

          <div className="space-y-4">
            <h2 className="text-lg font-semibold text-white/80">
              1. Description of Service
            </h2>
            <p className="text-sm leading-relaxed text-white/50">
              Digital Daily is a non-commercial, centralized news hub that
              aggregates headlines, short snippets, and thumbnail preview images
              from 19 public RSS feeds across Politics, Technology, Finance, and
              Sports.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-lg font-semibold text-white/80">
              2. Intellectual Property &amp; Fair Use
            </h2>
            <ul className="ml-4 space-y-3 text-sm text-white/50">
              <li>
                <span className="font-medium text-white/60">
                  Content Ownership:
                </span>{" "}
                Digital Daily does not claim ownership or copyright over any news
                articles, headlines, summaries, or imagery fetched from third-party
                networks. All rights belong exclusively to their respective
                publishers (e.g., BBC, Reuters, NY Times, TechCrunch).
              </li>
              <li>
                <span className="font-medium text-white/60">
                  Fair Use Compliance:
                </span>{" "}
                This platform strictly operates under global &quot;Fair Use&quot;
                copyright guidelines. We display only limited, non-commercial
                metadata (titles and short snippets) to provide a centralized
                index, and we explicitly provide direct outbound canonical links to
                drive traffic straight back to the copyright owner&apos;s original
                servers.
              </li>
              <li>
                <span className="font-medium text-white/60">
                  Content Removal:
                </span>{" "}
                If you are an intellectual property holder or publisher and wish to
                have your public RSS feed stream removed from our aggregator
                matrix, please contact us immediately, and the endpoint will be
                deleted within 48 hours.
              </li>
            </ul>
          </div>

          <div className="space-y-4">
            <h2 className="text-lg font-semibold text-white/80">
              3. Disclaimer of Liability
            </h2>
            <p className="text-sm leading-relaxed text-white/50">
              All news feeds are synchronized automatically in real-time. Digital
              Daily cannot guarantee the complete accuracy, truthfulness, integrity,
              or availability of content generated by independent news channels.
              Your utilization of third-party external links is done completely at
              your own risk.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-lg font-semibold text-white/80">
              4. Governing Law
            </h2>
            <p className="text-sm leading-relaxed text-white/50">
              These terms are governed by and construed in accordance with the laws
              of India, without regard to conflict of law principles.
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}
